export const route = {
  welcomeLogin: "/",
  confirmEmail: "/confirm-email",
  customerVoucher: "/voucher",
  admin: "/admin",
  dashboard: "dashboard",
  manageGym: "manage-gym",
  managePT: "manage-pt",
  managePackages: "manage-packages",
  manageUser: "manage-user",
  manageNotification: "manage-notification",
  manageTransaction: "manage-transaction",
  manageVoucher: "manage-voucher",
  manageWithdrawal: "manage-withdrawal",
  manageReport: "manage-report",
  manageProduct: "manage-product",
  manageOrder: "manage-order",
  manageContract: "manage-contract",
  manageCertificate: "manage-certificate",

  gym: "/gym",
  dashboardGym: "dashboard-gym",
  manageinformationGym: "manage-information-gym",
  manageUserGym: "manage-user-gym",
  managePTGym: "manage-pt-gym",
  managePackagesGym: "manage-packages-gym",
  manageTransactionGym: "manage-transaction-gym",
  manageSlotGym: "manage-slot-gym",
  manageVoucherGym: "manage-voucher-gym",
  contractSigning: "contract-signing",

  orderProcess: "order-process",

  freelancePt: "/freelance-pt",
  dashboardPT: "dashboard-pt",
  manageSchedulePT: "manage-schedule-pt",
  manageVoucherPT: "manage-voucher-pt",
  managePackageFPT: "manage-package-fpt",
};
